# Generated by Django 3.0.5 on 2020-05-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200503_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='user',
            new_name='user_saving',
        ),
    ]
